//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiCert.Demo.CertificateManagement
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", ConfigurationName="DigiCert.Demo.CertificateManagement.certificateManagementOperations")]
    public interface certificateManagementOperations
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2009/07/management/updateCertificateStatu" +
            "s", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.updateCertificateStatusResponse> updateCertificateStatusAsync(DigiCert.Demo.CertificateManagement.updateCertificateStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2009/07/management/bulkUpdateCertificateS" +
            "tatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.bulkUpdateCertificateStatusResponse> bulkUpdateCertificateStatusAsync(DigiCert.Demo.CertificateManagement.bulkUpdateCertificateStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2009/07/management/keyRecovery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.keyRecoveryResponse> keyRecoveryAsync(DigiCert.Demo.CertificateManagement.keyRecoveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2009/07/management/searchCertificate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.searchCertificateResponse> searchCertificateAsync(DigiCert.Demo.CertificateManagement.searchCertificateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class UpdateCertificateStatusRequestType
    {
        
        private string clientTransactionIDField;
        
        private string versionField;
        
        private string certificateIssuerField;
        
        private RevokeReasonCodeEnum revocationReasonField;
        
        private bool revocationReasonFieldSpecified;
        
        private string challengeField;
        
        private string commentField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private OperationTypeEnum operationTypeField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string certificateIssuer
        {
            get
            {
                return this.certificateIssuerField;
            }
            set
            {
                this.certificateIssuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RevokeReasonCodeEnum revocationReason
        {
            get
            {
                return this.revocationReasonField;
            }
            set
            {
                this.revocationReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revocationReasonSpecified
        {
            get
            {
                return this.revocationReasonFieldSpecified;
            }
            set
            {
                this.revocationReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string challenge
        {
            get
            {
                return this.challengeField;
            }
            set
            {
                this.challengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("certificateSerialNumber", typeof(string), Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("seatId", typeof(string), Order=6)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public OperationTypeEnum operationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="any", Order=9)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public enum RevokeReasonCodeEnum
    {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        KeyCompromise,
        
        /// <remarks/>
        CACompromise,
        
        /// <remarks/>
        AffiliationChanged,
        
        /// <remarks/>
        CessationOfOperation,
        
        /// <remarks/>
        PrivilegeWithdrawn,
        
        /// <remarks/>
        AACompromise,
        
        /// <remarks/>
        Superseded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        certificateSerialNumber,
        
        /// <remarks/>
        seatId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public enum OperationTypeEnum
    {
        
        /// <remarks/>
        Revoke,
        
        /// <remarks/>
        Suspend,
        
        /// <remarks/>
        Resume,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class CertificateSearchResultType
    {
        
        private byte[] certificateField;
        
        private string seatIdField;
        
        private string commonNameField;
        
        private string accountIdField;
        
        private string profileOIDField;
        
        private string emailAddressField;
        
        private CertificateStatusEnum statusField;
        
        private long revokeAtField;
        
        private bool revokeAtFieldSpecified;
        
        private RevokeReasonCodeEnum revokeReasonField;
        
        private bool revokeReasonFieldSpecified;
        
        private long validFromField;
        
        private long validToField;
        
        private string serialNumberField;
        
        private bool isEscrowedField;
        
        private string enrollmentNotesField;
        
        private string revokeCommentsField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string commonName
        {
            get
            {
                return this.commonNameField;
            }
            set
            {
                this.commonNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string profileOID
        {
            get
            {
                return this.profileOIDField;
            }
            set
            {
                this.profileOIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string emailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public CertificateStatusEnum status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long revokeAt
        {
            get
            {
                return this.revokeAtField;
            }
            set
            {
                this.revokeAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revokeAtSpecified
        {
            get
            {
                return this.revokeAtFieldSpecified;
            }
            set
            {
                this.revokeAtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public RevokeReasonCodeEnum revokeReason
        {
            get
            {
                return this.revokeReasonField;
            }
            set
            {
                this.revokeReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revokeReasonSpecified
        {
            get
            {
                return this.revokeReasonFieldSpecified;
            }
            set
            {
                this.revokeReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long validTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string serialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool isEscrowed
        {
            get
            {
                return this.isEscrowedField;
            }
            set
            {
                this.isEscrowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string enrollmentNotes
        {
            get
            {
                return this.enrollmentNotesField;
            }
            set
            {
                this.enrollmentNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string revokeComments
        {
            get
            {
                return this.revokeCommentsField;
            }
            set
            {
                this.revokeCommentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=15)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public enum CertificateStatusEnum
    {
        
        /// <remarks/>
        VALID,
        
        /// <remarks/>
        EXPIRED,
        
        /// <remarks/>
        REVOKED,
        
        /// <remarks/>
        SUSPENDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class SearchCertificateResponseType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private int certificateCountField;
        
        private CertificateSearchResultType[] certificateListField;
        
        private bool moreCertificateAvailableField;
        
        private bool moreCertificateAvailableFieldSpecified;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int certificateCount
        {
            get
            {
                return this.certificateCountField;
            }
            set
            {
                this.certificateCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("certificateInformation", IsNullable=false)]
        public CertificateSearchResultType[] certificateList
        {
            get
            {
                return this.certificateListField;
            }
            set
            {
                this.certificateListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool moreCertificateAvailable
        {
            get
            {
                return this.moreCertificateAvailableField;
            }
            set
            {
                this.moreCertificateAvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool moreCertificateAvailableSpecified
        {
            get
            {
                return this.moreCertificateAvailableFieldSpecified;
            }
            set
            {
                this.moreCertificateAvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class SearchCertificateRequestType
    {
        
        private string clientTransactionIDField;
        
        private string seatIdField;
        
        private string accountIdField;
        
        private string profileOIDField;
        
        private string commonNameField;
        
        private CertificateStatusEnum statusField;
        
        private bool statusFieldSpecified;
        
        private string emailAddressField;
        
        private string serialNumberField;
        
        private byte[] issuingCAField;
        
        private long validFromField;
        
        private bool validFromFieldSpecified;
        
        private long validToField;
        
        private bool validToFieldSpecified;
        
        private int startIndexField;
        
        private bool startIndexFieldSpecified;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string profileOID
        {
            get
            {
                return this.profileOIDField;
            }
            set
            {
                this.profileOIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string commonName
        {
            get
            {
                return this.commonNameField;
            }
            set
            {
                this.commonNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CertificateStatusEnum status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string emailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string serialNumber
        {
            get
            {
                return this.serialNumberField;
            }
            set
            {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=8)]
        public byte[] issuingCA
        {
            get
            {
                return this.issuingCAField;
            }
            set
            {
                this.issuingCAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validFromSpecified
        {
            get
            {
                return this.validFromFieldSpecified;
            }
            set
            {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long validTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validToSpecified
        {
            get
            {
                return this.validToFieldSpecified;
            }
            set
            {
                this.validToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int startIndex
        {
            get
            {
                return this.startIndexField;
            }
            set
            {
                this.startIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startIndexSpecified
        {
            get
            {
                return this.startIndexFieldSpecified;
            }
            set
            {
                this.startIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=13)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class RequestKeyRecoveryResponseMessageType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private int adminApprovalPendingCountField;
        
        private bool adminApprovalPendingCountFieldSpecified;
        
        private string pKCS12PasswordField;
        
        private string[] pKCS12MessageField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int adminApprovalPendingCount
        {
            get
            {
                return this.adminApprovalPendingCountField;
            }
            set
            {
                this.adminApprovalPendingCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adminApprovalPendingCountSpecified
        {
            get
            {
                return this.adminApprovalPendingCountFieldSpecified;
            }
            set
            {
                this.adminApprovalPendingCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string pKCS12Password
        {
            get
            {
                return this.pKCS12PasswordField;
            }
            set
            {
                this.pKCS12PasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pKCS12Message", Order=4)]
        public string[] pKCS12Message
        {
            get
            {
                return this.pKCS12MessageField;
            }
            set
            {
                this.pKCS12MessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class RequestKeyRecoveryMessageType
    {
        
        private string clientTransactionIDField;
        
        private string pKCS12PasswordField;
        
        private string certificateSerialNumberField;
        
        private string certificateIssuerField;
        
        private string adminIDField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pKCS12Password
        {
            get
            {
                return this.pKCS12PasswordField;
            }
            set
            {
                this.pKCS12PasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string certificateSerialNumber
        {
            get
            {
                return this.certificateSerialNumberField;
            }
            set
            {
                this.certificateSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string certificateIssuer
        {
            get
            {
                return this.certificateIssuerField;
            }
            set
            {
                this.certificateIssuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string adminID
        {
            get
            {
                return this.adminIDField;
            }
            set
            {
                this.adminIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class BulkUpdateCertificateStatusResponseType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private string versionField;
        
        private int successCodeField;
        
        private string successMsgField;
        
        private int revocationCountField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int successCode
        {
            get
            {
                return this.successCodeField;
            }
            set
            {
                this.successCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string successMsg
        {
            get
            {
                return this.successMsgField;
            }
            set
            {
                this.successMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int revocationCount
        {
            get
            {
                return this.revocationCountField;
            }
            set
            {
                this.revocationCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class BulkUpdateCertificateStatusRequestType
    {
        
        private string clientTransactionIDField;
        
        private string versionField;
        
        private RevokeReasonCodeEnum revocationReasonField;
        
        private bool revocationReasonFieldSpecified;
        
        private string commentField;
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private OperationTypeEnum operationTypeField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RevokeReasonCodeEnum revocationReason
        {
            get
            {
                return this.revocationReasonField;
            }
            set
            {
                this.revocationReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revocationReasonSpecified
        {
            get
            {
                return this.revocationReasonFieldSpecified;
            }
            set
            {
                this.revocationReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("certificateSerialNumber", typeof(string), Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("profileOID", typeof(string), Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("seatId", typeof(string), Order=4)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=5)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public OperationTypeEnum operationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="any", Order=7)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        certificateSerialNumber,
        
        /// <remarks/>
        profileOID,
        
        /// <remarks/>
        seatId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management")]
    public partial class UpdateCertificateStatusResponseType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private string versionField;
        
        private int successCodeField;
        
        private string successMsgField;
        
        private int revocationCountField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int successCode
        {
            get
            {
                return this.successCodeField;
            }
            set
            {
                this.successCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string successMsg
        {
            get
            {
                return this.successMsgField;
            }
            set
            {
                this.successMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int revocationCount
        {
            get
            {
                return this.revocationCountField;
            }
            set
            {
                this.revocationCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCertificateStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCertificateStatusRequest", Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.UpdateCertificateStatusRequestType updateCertificateStatusRequest1;
        
        public updateCertificateStatusRequest()
        {
        }
        
        public updateCertificateStatusRequest(DigiCert.Demo.CertificateManagement.UpdateCertificateStatusRequestType updateCertificateStatusRequest1)
        {
            this.updateCertificateStatusRequest1 = updateCertificateStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCertificateStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCertificateStatusResponse", Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.UpdateCertificateStatusResponseType updateCertificateStatusResponse1;
        
        public updateCertificateStatusResponse()
        {
        }
        
        public updateCertificateStatusResponse(DigiCert.Demo.CertificateManagement.UpdateCertificateStatusResponseType updateCertificateStatusResponse1)
        {
            this.updateCertificateStatusResponse1 = updateCertificateStatusResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bulkUpdateCertificateStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bulkUpdateCertificateStatusRequest", Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.BulkUpdateCertificateStatusRequestType bulkUpdateCertificateStatusRequest1;
        
        public bulkUpdateCertificateStatusRequest()
        {
        }
        
        public bulkUpdateCertificateStatusRequest(DigiCert.Demo.CertificateManagement.BulkUpdateCertificateStatusRequestType bulkUpdateCertificateStatusRequest1)
        {
            this.bulkUpdateCertificateStatusRequest1 = bulkUpdateCertificateStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bulkUpdateCertificateStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bulkUpdateCertificateStatusResponse", Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.BulkUpdateCertificateStatusResponseType bulkUpdateCertificateStatusResponse1;
        
        public bulkUpdateCertificateStatusResponse()
        {
        }
        
        public bulkUpdateCertificateStatusResponse(DigiCert.Demo.CertificateManagement.BulkUpdateCertificateStatusResponseType bulkUpdateCertificateStatusResponse1)
        {
            this.bulkUpdateCertificateStatusResponse1 = bulkUpdateCertificateStatusResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class keyRecoveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.RequestKeyRecoveryMessageType requestKeyRecoveryMessage;
        
        public keyRecoveryRequest()
        {
        }
        
        public keyRecoveryRequest(DigiCert.Demo.CertificateManagement.RequestKeyRecoveryMessageType requestKeyRecoveryMessage)
        {
            this.requestKeyRecoveryMessage = requestKeyRecoveryMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class keyRecoveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.RequestKeyRecoveryResponseMessageType requestKeyRecoveryResponseMessage;
        
        public keyRecoveryResponse()
        {
        }
        
        public keyRecoveryResponse(DigiCert.Demo.CertificateManagement.RequestKeyRecoveryResponseMessageType requestKeyRecoveryResponseMessage)
        {
            this.requestKeyRecoveryResponseMessage = requestKeyRecoveryResponseMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCertificateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchCertificateRequest", Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.SearchCertificateRequestType searchCertificateRequest1;
        
        public searchCertificateRequest()
        {
        }
        
        public searchCertificateRequest(DigiCert.Demo.CertificateManagement.SearchCertificateRequestType searchCertificateRequest1)
        {
            this.searchCertificateRequest1 = searchCertificateRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCertificateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchCertificateResponse", Namespace="http://schemas.verisign.com/pkiservices/2009/07/management", Order=0)]
        public DigiCert.Demo.CertificateManagement.SearchCertificateResponseType searchCertificateResponse1;
        
        public searchCertificateResponse()
        {
        }
        
        public searchCertificateResponse(DigiCert.Demo.CertificateManagement.SearchCertificateResponseType searchCertificateResponse1)
        {
            this.searchCertificateResponse1 = searchCertificateResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface certificateManagementOperationsChannel : DigiCert.Demo.CertificateManagement.certificateManagementOperations, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class certificateManagementOperationsClient : System.ServiceModel.ClientBase<DigiCert.Demo.CertificateManagement.certificateManagementOperations>, DigiCert.Demo.CertificateManagement.certificateManagementOperations
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public certificateManagementOperationsClient() : 
                base(certificateManagementOperationsClient.GetDefaultBinding(), certificateManagementOperationsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.certificateManagementServiceSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public certificateManagementOperationsClient(EndpointConfiguration endpointConfiguration) : 
                base(certificateManagementOperationsClient.GetBindingForEndpoint(endpointConfiguration), certificateManagementOperationsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public certificateManagementOperationsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(certificateManagementOperationsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public certificateManagementOperationsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(certificateManagementOperationsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public certificateManagementOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.updateCertificateStatusResponse> DigiCert.Demo.CertificateManagement.certificateManagementOperations.updateCertificateStatusAsync(DigiCert.Demo.CertificateManagement.updateCertificateStatusRequest request)
        {
            return base.Channel.updateCertificateStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.updateCertificateStatusResponse> updateCertificateStatusAsync(DigiCert.Demo.CertificateManagement.UpdateCertificateStatusRequestType updateCertificateStatusRequest1)
        {
            DigiCert.Demo.CertificateManagement.updateCertificateStatusRequest inValue = new DigiCert.Demo.CertificateManagement.updateCertificateStatusRequest();
            inValue.updateCertificateStatusRequest1 = updateCertificateStatusRequest1;
            return ((DigiCert.Demo.CertificateManagement.certificateManagementOperations)(this)).updateCertificateStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.bulkUpdateCertificateStatusResponse> DigiCert.Demo.CertificateManagement.certificateManagementOperations.bulkUpdateCertificateStatusAsync(DigiCert.Demo.CertificateManagement.bulkUpdateCertificateStatusRequest request)
        {
            return base.Channel.bulkUpdateCertificateStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.bulkUpdateCertificateStatusResponse> bulkUpdateCertificateStatusAsync(DigiCert.Demo.CertificateManagement.BulkUpdateCertificateStatusRequestType bulkUpdateCertificateStatusRequest1)
        {
            DigiCert.Demo.CertificateManagement.bulkUpdateCertificateStatusRequest inValue = new DigiCert.Demo.CertificateManagement.bulkUpdateCertificateStatusRequest();
            inValue.bulkUpdateCertificateStatusRequest1 = bulkUpdateCertificateStatusRequest1;
            return ((DigiCert.Demo.CertificateManagement.certificateManagementOperations)(this)).bulkUpdateCertificateStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.keyRecoveryResponse> DigiCert.Demo.CertificateManagement.certificateManagementOperations.keyRecoveryAsync(DigiCert.Demo.CertificateManagement.keyRecoveryRequest request)
        {
            return base.Channel.keyRecoveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.keyRecoveryResponse> keyRecoveryAsync(DigiCert.Demo.CertificateManagement.RequestKeyRecoveryMessageType requestKeyRecoveryMessage)
        {
            DigiCert.Demo.CertificateManagement.keyRecoveryRequest inValue = new DigiCert.Demo.CertificateManagement.keyRecoveryRequest();
            inValue.requestKeyRecoveryMessage = requestKeyRecoveryMessage;
            return ((DigiCert.Demo.CertificateManagement.certificateManagementOperations)(this)).keyRecoveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.searchCertificateResponse> DigiCert.Demo.CertificateManagement.certificateManagementOperations.searchCertificateAsync(DigiCert.Demo.CertificateManagement.searchCertificateRequest request)
        {
            return base.Channel.searchCertificateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.CertificateManagement.searchCertificateResponse> searchCertificateAsync(DigiCert.Demo.CertificateManagement.SearchCertificateRequestType searchCertificateRequest1)
        {
            DigiCert.Demo.CertificateManagement.searchCertificateRequest inValue = new DigiCert.Demo.CertificateManagement.searchCertificateRequest();
            inValue.searchCertificateRequest1 = searchCertificateRequest1;
            return ((DigiCert.Demo.CertificateManagement.certificateManagementOperations)(this)).searchCertificateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.certificateManagementServiceSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.certificateManagementServiceSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://pki-ws.symauth.com/pki-ws/certificateManagementService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return certificateManagementOperationsClient.GetBindingForEndpoint(EndpointConfiguration.certificateManagementServiceSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return certificateManagementOperationsClient.GetEndpointAddress(EndpointConfiguration.certificateManagementServiceSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            certificateManagementServiceSOAP,
        }
    }
}
