//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiCert.Demo.Enrollment
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/", ConfigurationName="DigiCert.Demo.Enrollment.WSSecurityRequestor")]
    public interface WSSecurityRequestor
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/WSSecurityRequestor/SecurityToke" +
            "nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task SecurityTokenResponseAsync(DigiCert.Demo.Enrollment.SecurityTokenResponse request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/WSSecurityRequestor/SecurityToke" +
            "nResponse2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task SecurityTokenResponse2Async(DigiCert.Demo.Enrollment.SecurityTokenResponse2 request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/WSSecurityRequestor/ChallengeReq" +
            "uest", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/WSSecurityRequestor/ChallengeRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse> ChallengeAsync(DigiCert.Demo.Enrollment.SecurityTokenResponse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/WSSecurityRequestor/Challenge2Re" +
            "quest", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/WSSecurityRequestor/Challenge2Re" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse2> Challenge2Async(DigiCert.Demo.Enrollment.SecurityTokenResponse request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/")]
    public partial class RequestSecurityTokenResponseType
    {
        
        private RequestVSSecurityTokenResponseEnrollmentType itemField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestVSSecurityTokenResponse", Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment", Order=0)]
        public RequestVSSecurityTokenResponseEnrollmentType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment")]
    public partial class RequestVSSecurityTokenResponseEnrollmentType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private TokenType tokenTypeField;
        
        private bool tokenTypeFieldSpecified;
        
        private string dispositionMessageField;
        
        private BinarySecurityTokenType binarySecurityTokenField;
        
        private RequestedVSSecurityTokenEnrollmentType requestedVSSecurityTokenField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string preferredLanguageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TokenType tokenType
        {
            get
            {
                return this.tokenTypeField;
            }
            set
            {
                this.tokenTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tokenTypeSpecified
        {
            get
            {
                return this.tokenTypeFieldSpecified;
            }
            set
            {
                this.tokenTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dispositionMessage
        {
            get
            {
                return this.dispositionMessageField;
            }
            set
            {
                this.dispositionMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public BinarySecurityTokenType binarySecurityToken
        {
            get
            {
                return this.binarySecurityTokenField;
            }
            set
            {
                this.binarySecurityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public RequestedVSSecurityTokenEnrollmentType requestedVSSecurityToken
        {
            get
            {
                return this.requestedVSSecurityTokenField;
            }
            set
            {
                this.requestedVSSecurityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment", Order=7)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string preferredLanguage
        {
            get
            {
                return this.preferredLanguageField;
            }
            set
            {
                this.preferredLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment")]
    public enum TokenType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X5" +
            "09v3")]
        httpdocsoasisopenorgwss200401oasis200401wssx509tokenprofile10X509v3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#PK" +
            "CS7")]
        httpdocsoasisopenorgwss200401oasis200401wssx509tokenprofile10PKCS7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://schemas.verisign.com/pkiservices/2009/07/PKCS12")]
        httpschemasverisigncompkiservices200907PKCS12,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class BinarySecurityTokenType : EncodedString
    {
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ValueType
        {
            get
            {
                return this.valueTypeField;
            }
            set
            {
                this.valueTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySecurityTokenType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class EncodedString : AttributedString
    {
        
        private string encodingTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string EncodingType
        {
            get
            {
                return this.encodingTypeField;
            }
            set
            {
                this.encodingTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EncodedString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinarySecurityTokenType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PasswordString))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class AttributedString
    {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d", DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment")]
    public partial class NameValueType
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2006/12/authorization")]
    public partial class ContextItemType
    {
        
        private object itemField;
        
        private string nameField;
        
        private string scopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Value", typeof(string), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Scope
        {
            get
            {
                return this.scopeField;
            }
            set
            {
                this.scopeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2006/12/authorization")]
    public partial class AdditionalContextType
    {
        
        private ContextItemType[] contextItemField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContextItem", Order=0)]
        public ContextItemType[] ContextItem
        {
            get
            {
                return this.contextItemField;
            }
            set
            {
                this.contextItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment")]
    public partial class RequestVSSecurityTokenEnrollmentType
    {
        
        private string certificateProfileIDField;
        
        private string clientTransactionIDField;
        
        private TokenType tokenTypeField;
        
        private bool tokenTypeFieldSpecified;
        
        private RequestTypeEnum requestTypeField;
        
        private BinarySecurityTokenType[] binarySecurityTokenField;
        
        private AdditionalContextType additionalContextField;
        
        private string pendingTokenReferenceIDField;
        
        private NameValueType[] nameValuePairField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string preferredLanguageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string certificateProfileID
        {
            get
            {
                return this.certificateProfileIDField;
            }
            set
            {
                this.certificateProfileIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TokenType tokenType
        {
            get
            {
                return this.tokenTypeField;
            }
            set
            {
                this.tokenTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tokenTypeSpecified
        {
            get
            {
                return this.tokenTypeFieldSpecified;
            }
            set
            {
                this.tokenTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RequestTypeEnum requestType
        {
            get
            {
                return this.requestTypeField;
            }
            set
            {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("binarySecurityToken", Order=4)]
        public BinarySecurityTokenType[] binarySecurityToken
        {
            get
            {
                return this.binarySecurityTokenField;
            }
            set
            {
                this.binarySecurityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AdditionalContextType additionalContext
        {
            get
            {
                return this.additionalContextField;
            }
            set
            {
                this.additionalContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string pendingTokenReferenceID
        {
            get
            {
                return this.pendingTokenReferenceIDField;
            }
            set
            {
                this.pendingTokenReferenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nameValuePair", Order=7)]
        public NameValueType[] nameValuePair
        {
            get
            {
                return this.nameValuePairField;
            }
            set
            {
                this.nameValuePairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=9)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string preferredLanguage
        {
            get
            {
                return this.preferredLanguageField;
            }
            set
            {
                this.preferredLanguageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment")]
    public enum RequestTypeEnum
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue")]
        httpdocsoasisopenorgwssxwstrust200512Issue,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://docs.oasis-open.org/ws-sx/ws-trust/200512/Renew")]
        httpdocsoasisopenorgwssxwstrust200512Renew,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://schemas.verisign.com/pkiservices/2009/07/QueryTokenStatus")]
        httpschemasverisigncompkiservices200907QueryTokenStatus,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/")]
    public partial class RequestSecurityTokenType
    {
        
        private RequestVSSecurityTokenEnrollmentType itemField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestVSSecurityToken", Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment", Order=0)]
        public RequestVSSecurityTokenEnrollmentType Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/")]
    public partial class RequestSecurityTokenResponseCollectionType
    {
        
        private RequestSecurityTokenResponseType[] requestSecurityTokenResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequestSecurityTokenResponse", Order=0)]
        public RequestSecurityTokenResponseType[] RequestSecurityTokenResponse
        {
            get
            {
                return this.requestSecurityTokenResponseField;
            }
            set
            {
                this.requestSecurityTokenResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment")]
    public partial class RequestedVSSecurityTokenEnrollmentType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("binarySecurityToken", typeof(BinarySecurityTokenType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("pKCS12Password", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("pendingTokenReferenceID", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/enrollment", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        binarySecurityToken,
        
        /// <remarks/>
        pKCS12Password,
        
        /// <remarks/>
        pendingTokenReferenceID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class PasswordString : AttributedString
    {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class KeyIdentifierType : EncodedString
    {
        
        private string valueTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string ValueType
        {
            get
            {
                return this.valueTypeField;
            }
            set
            {
                this.valueTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecurityTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/", Order=0)]
        public DigiCert.Demo.Enrollment.RequestSecurityTokenResponseType RequestSecurityTokenResponse;
        
        public SecurityTokenResponse()
        {
        }
        
        public SecurityTokenResponse(DigiCert.Demo.Enrollment.RequestSecurityTokenResponseType RequestSecurityTokenResponse)
        {
            this.RequestSecurityTokenResponse = RequestSecurityTokenResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecurityTokenResponse2
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/", Order=0)]
        public DigiCert.Demo.Enrollment.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection;
        
        public SecurityTokenResponse2()
        {
        }
        
        public SecurityTokenResponse2(DigiCert.Demo.Enrollment.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection)
        {
            this.RequestSecurityTokenResponseCollection = RequestSecurityTokenResponseCollection;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface WSSecurityRequestorChannel : DigiCert.Demo.Enrollment.WSSecurityRequestor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class WSSecurityRequestorClient : System.ServiceModel.ClientBase<DigiCert.Demo.Enrollment.WSSecurityRequestor>, DigiCert.Demo.Enrollment.WSSecurityRequestor
    {
        
        public WSSecurityRequestorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task DigiCert.Demo.Enrollment.WSSecurityRequestor.SecurityTokenResponseAsync(DigiCert.Demo.Enrollment.SecurityTokenResponse request)
        {
            return base.Channel.SecurityTokenResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task SecurityTokenResponseAsync(DigiCert.Demo.Enrollment.RequestSecurityTokenResponseType RequestSecurityTokenResponse)
        {
            DigiCert.Demo.Enrollment.SecurityTokenResponse inValue = new DigiCert.Demo.Enrollment.SecurityTokenResponse();
            inValue.RequestSecurityTokenResponse = RequestSecurityTokenResponse;
            return ((DigiCert.Demo.Enrollment.WSSecurityRequestor)(this)).SecurityTokenResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task DigiCert.Demo.Enrollment.WSSecurityRequestor.SecurityTokenResponse2Async(DigiCert.Demo.Enrollment.SecurityTokenResponse2 request)
        {
            return base.Channel.SecurityTokenResponse2Async(request);
        }
        
        public System.Threading.Tasks.Task SecurityTokenResponse2Async(DigiCert.Demo.Enrollment.RequestSecurityTokenResponseCollectionType RequestSecurityTokenResponseCollection)
        {
            DigiCert.Demo.Enrollment.SecurityTokenResponse2 inValue = new DigiCert.Demo.Enrollment.SecurityTokenResponse2();
            inValue.RequestSecurityTokenResponseCollection = RequestSecurityTokenResponseCollection;
            return ((DigiCert.Demo.Enrollment.WSSecurityRequestor)(this)).SecurityTokenResponse2Async(inValue);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse> ChallengeAsync(DigiCert.Demo.Enrollment.SecurityTokenResponse request)
        {
            return base.Channel.ChallengeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse2> DigiCert.Demo.Enrollment.WSSecurityRequestor.Challenge2Async(DigiCert.Demo.Enrollment.SecurityTokenResponse request)
        {
            return base.Channel.Challenge2Async(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse2> Challenge2Async(DigiCert.Demo.Enrollment.RequestSecurityTokenResponseType RequestSecurityTokenResponse)
        {
            DigiCert.Demo.Enrollment.SecurityTokenResponse inValue = new DigiCert.Demo.Enrollment.SecurityTokenResponse();
            inValue.RequestSecurityTokenResponse = RequestSecurityTokenResponse;
            return ((DigiCert.Demo.Enrollment.WSSecurityRequestor)(this)).Challenge2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/", ConfigurationName="DigiCert.Demo.Enrollment.SecurityTokenRequestService")]
    public interface SecurityTokenRequestService
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/SecurityTokenRequestService/Requ" +
            "estSecurityToken")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task RequestSecurityTokenAsync(DigiCert.Demo.Enrollment.RequestSecurityToken request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/SecurityTokenRequestService/Requ" +
            "estSecurityTokenCollection")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task RequestSecurityTokenCollectionAsync(DigiCert.Demo.Enrollment.RequestSecurityTokenCollection request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestSecurityToken
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestSecurityToken", Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/", Order=0)]
        public DigiCert.Demo.Enrollment.RequestSecurityTokenType RequestSecurityToken1;
        
        public RequestSecurityToken()
        {
        }
        
        public RequestSecurityToken(DigiCert.Demo.Enrollment.RequestSecurityTokenType RequestSecurityToken1)
        {
            this.RequestSecurityToken1 = RequestSecurityToken1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestSecurityTokenCollection
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestSecurityTokenCollection", Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RequestSecurityToken", IsNullable=false)]
        public DigiCert.Demo.Enrollment.RequestSecurityTokenType[] RequestSecurityTokenCollection1;
        
        public RequestSecurityTokenCollection()
        {
        }
        
        public RequestSecurityTokenCollection(DigiCert.Demo.Enrollment.RequestSecurityTokenType[] RequestSecurityTokenCollection1)
        {
            this.RequestSecurityTokenCollection1 = RequestSecurityTokenCollection1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface SecurityTokenRequestServiceChannel : DigiCert.Demo.Enrollment.SecurityTokenRequestService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class SecurityTokenRequestServiceClient : System.ServiceModel.ClientBase<DigiCert.Demo.Enrollment.SecurityTokenRequestService>, DigiCert.Demo.Enrollment.SecurityTokenRequestService
    {
        
        public SecurityTokenRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task DigiCert.Demo.Enrollment.SecurityTokenRequestService.RequestSecurityTokenAsync(DigiCert.Demo.Enrollment.RequestSecurityToken request)
        {
            return base.Channel.RequestSecurityTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task RequestSecurityTokenAsync(DigiCert.Demo.Enrollment.RequestSecurityTokenType RequestSecurityToken1)
        {
            DigiCert.Demo.Enrollment.RequestSecurityToken inValue = new DigiCert.Demo.Enrollment.RequestSecurityToken();
            inValue.RequestSecurityToken1 = RequestSecurityToken1;
            return ((DigiCert.Demo.Enrollment.SecurityTokenRequestService)(this)).RequestSecurityTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task DigiCert.Demo.Enrollment.SecurityTokenRequestService.RequestSecurityTokenCollectionAsync(DigiCert.Demo.Enrollment.RequestSecurityTokenCollection request)
        {
            return base.Channel.RequestSecurityTokenCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task RequestSecurityTokenCollectionAsync(DigiCert.Demo.Enrollment.RequestSecurityTokenType[] RequestSecurityTokenCollection1)
        {
            DigiCert.Demo.Enrollment.RequestSecurityTokenCollection inValue = new DigiCert.Demo.Enrollment.RequestSecurityTokenCollection();
            inValue.RequestSecurityTokenCollection1 = RequestSecurityTokenCollection1;
            return ((DigiCert.Demo.Enrollment.SecurityTokenRequestService)(this)).RequestSecurityTokenCollectionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/", ConfigurationName="DigiCert.Demo.Enrollment.SecurityTokenService")]
    public interface SecurityTokenService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/SecurityTokenService/RequestSecu" +
            "rityTokenRequest", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/SecurityTokenService/RequestSecu" +
            "rityTokenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse> RequestSecurityTokenAsync(DigiCert.Demo.Enrollment.RequestSecurityToken request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/SecurityTokenService/RequestSecu" +
            "rityToken2Request", ReplyAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/SecurityTokenService/RequestSecu" +
            "rityToken2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedString))]
        System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse2> RequestSecurityToken2Async(DigiCert.Demo.Enrollment.RequestSecurityToken request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface SecurityTokenServiceChannel : DigiCert.Demo.Enrollment.SecurityTokenService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class SecurityTokenServiceClient : System.ServiceModel.ClientBase<DigiCert.Demo.Enrollment.SecurityTokenService>, DigiCert.Demo.Enrollment.SecurityTokenService
    {
        
        public SecurityTokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse> DigiCert.Demo.Enrollment.SecurityTokenService.RequestSecurityTokenAsync(DigiCert.Demo.Enrollment.RequestSecurityToken request)
        {
            return base.Channel.RequestSecurityTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse> RequestSecurityTokenAsync(DigiCert.Demo.Enrollment.RequestSecurityTokenType RequestSecurityToken1)
        {
            DigiCert.Demo.Enrollment.RequestSecurityToken inValue = new DigiCert.Demo.Enrollment.RequestSecurityToken();
            inValue.RequestSecurityToken1 = RequestSecurityToken1;
            return ((DigiCert.Demo.Enrollment.SecurityTokenService)(this)).RequestSecurityTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse2> DigiCert.Demo.Enrollment.SecurityTokenService.RequestSecurityToken2Async(DigiCert.Demo.Enrollment.RequestSecurityToken request)
        {
            return base.Channel.RequestSecurityToken2Async(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.Enrollment.SecurityTokenResponse2> RequestSecurityToken2Async(DigiCert.Demo.Enrollment.RequestSecurityTokenType RequestSecurityToken1)
        {
            DigiCert.Demo.Enrollment.RequestSecurityToken inValue = new DigiCert.Demo.Enrollment.RequestSecurityToken();
            inValue.RequestSecurityToken1 = RequestSecurityToken1;
            return ((DigiCert.Demo.Enrollment.SecurityTokenService)(this)).RequestSecurityToken2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
