//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiCert.Demo.Policy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy", ConfigurationName="DigiCert.Demo.Policy.policy")]
    public interface policy
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2009/07/policy/getPolicies", ReplyAction="http://schemas.verisign.com/pkiservices/2009/07/policy/getPoliciesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.Policy.requestPoliciesResponse> requestPoliciesAsync(DigiCert.Demo.Policy.requestPoliciesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class getPolicies
    {
        
        private string versionField;
        
        private string clientTransactionIDField;
        
        private Client clientField;
        
        private RequestFilter requestFilterField;
        
        private bool signResponseField;
        
        private bool signResponseFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Client client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public RequestFilter requestFilter
        {
            get
            {
                return this.requestFilterField;
            }
            set
            {
                this.requestFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool signResponse
        {
            get
            {
                return this.signResponseField;
            }
            set
            {
                this.signResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signResponseSpecified
        {
            get
            {
                return this.signResponseFieldSpecified;
            }
            set
            {
                this.signResponseFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class Client
    {
        
        private System.Nullable<System.DateTime> lastUpdatetimeField;
        
        private string preferredLanguageField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> lastUpdatetime
        {
            get
            {
                return this.lastUpdatetimeField;
            }
            set
            {
                this.lastUpdatetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="language", IsNullable=true, Order=1)]
        public string preferredLanguage
        {
            get
            {
                return this.preferredLanguageField;
            }
            set
            {
                this.preferredLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class OID
    {
        
        private string valueField;
        
        private int oIDReferenceIDField;
        
        private uint groupField;
        
        private string defaultNameField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int oIDReferenceID
        {
            get
            {
                return this.oIDReferenceIDField;
            }
            set
            {
                this.oIDReferenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public uint group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string defaultName
        {
            get
            {
                return this.defaultNameField;
            }
            set
            {
                this.defaultNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class CA
    {
        
        private string[] urisField;
        
        private byte[] certificateField;
        
        private string cAIssuerNameField;
        
        private int cAReferenceIDField;
        
        private System.Nullable<CAType> cATypeField;
        
        private byte[][] intermediateCACertificatesField;
        
        private byte[] rootCACertificateField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uris", DataType="anyURI", Order=0)]
        public string[] uris
        {
            get
            {
                return this.urisField;
            }
            set
            {
                this.urisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string cAIssuerName
        {
            get
            {
                return this.cAIssuerNameField;
            }
            set
            {
                this.cAIssuerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int cAReferenceID
        {
            get
            {
                return this.cAReferenceIDField;
            }
            set
            {
                this.cAReferenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<CAType> cAType
        {
            get
            {
                return this.cATypeField;
            }
            set
            {
                this.cATypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("intermediateCACertificates", DataType="base64Binary", Order=5)]
        public byte[][] intermediateCACertificates
        {
            get
            {
                return this.intermediateCACertificatesField;
            }
            set
            {
                this.intermediateCACertificatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] rootCACertificate
        {
            get
            {
                return this.rootCACertificateField;
            }
            set
            {
                this.rootCACertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=7)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public enum CAType
    {
        
        /// <remarks/>
        @public,
        
        /// <remarks/>
        @private,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class MigrationOIDCollection
    {
        
        private string[] migratedFromOIDField;
        
        private string migratedToOIDField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("migratedFromOID", Order=0)]
        public string[] migratedFromOID
        {
            get
            {
                return this.migratedFromOIDField;
            }
            set
            {
                this.migratedFromOIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string migratedToOID
        {
            get
            {
                return this.migratedToOIDField;
            }
            set
            {
                this.migratedToOIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class ApplicationInstructionsType
    {
        
        private string fileContentTypeField;
        
        private string urlField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileContentType
        {
            get
            {
                return this.fileContentTypeField;
            }
            set
            {
                this.fileContentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class SeatInfoType
    {
        
        private AttributeValueType attributeNameValueField;
        
        private AttributeNameValuePropertyType attributeNameValuePropertyField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributeValueType attributeNameValue
        {
            get
            {
                return this.attributeNameValueField;
            }
            set
            {
                this.attributeNameValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AttributeNameValuePropertyType attributeNameValueProperty
        {
            get
            {
                return this.attributeNameValuePropertyField;
            }
            set
            {
                this.attributeNameValuePropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class AttributeValueType
    {
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory
        {
            get
            {
                return this.mandatoryField;
            }
            set
            {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified
        {
            get
            {
                return this.mandatoryFieldSpecified;
            }
            set
            {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class AttributeNameValuePropertyType
    {
        
        private string valueField;
        
        private string sourceField;
        
        private string sourceAttributeNameField;
        
        private System.Nullable<bool> mandatoryField;
        
        private System.Nullable<bool> overridableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sourceAttributeName
        {
            get
            {
                return this.sourceAttributeNameField;
            }
            set
            {
                this.sourceAttributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> mandatory
        {
            get
            {
                return this.mandatoryField;
            }
            set
            {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> overridable
        {
            get
            {
                return this.overridableField;
            }
            set
            {
                this.overridableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class PollingTimeType
    {
        
        private int nextUpdateHoursField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int nextUpdateHours
        {
            get
            {
                return this.nextUpdateHoursField;
            }
            set
            {
                this.nextUpdateHoursField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class PollingPolicyType
    {
        
        private PollingTimeType gatewayPollingTimeField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PollingTimeType gatewayPollingTime
        {
            get
            {
                return this.gatewayPollingTimeField;
            }
            set
            {
                this.gatewayPollingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class DirectoryInfoType
    {
        
        private string directoryTypeField;
        
        private string domainNameField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string directoryType
        {
            get
            {
                return this.directoryTypeField;
            }
            set
            {
                this.directoryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string domainName
        {
            get
            {
                return this.domainNameField;
            }
            set
            {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hostName", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("ipAddress", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        hostName,
        
        /// <remarks/>
        ipAddress,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class AuthorizationInfoType
    {
        
        private string[] userAuthorizationCollectionField;
        
        private DirectoryInfoType directoryInfoField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("authorizedGroup", IsNullable=false)]
        public string[] userAuthorizationCollection
        {
            get
            {
                return this.userAuthorizationCollectionField;
            }
            set
            {
                this.userAuthorizationCollectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public DirectoryInfoType directoryInfo
        {
            get
            {
                return this.directoryInfoField;
            }
            set
            {
                this.directoryInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class RAPolicy
    {
        
        private bool registerUserField;
        
        private bool verifyUserField;
        
        private PublishCert publishCertField;
        
        private AuthorizationInfoType[] authorizationInfoField;
        
        private PollingPolicyType pollingPolicyField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool registerUser
        {
            get
            {
                return this.registerUserField;
            }
            set
            {
                this.registerUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool verifyUser
        {
            get
            {
                return this.verifyUserField;
            }
            set
            {
                this.verifyUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PublishCert publishCert
        {
            get
            {
                return this.publishCertField;
            }
            set
            {
                this.publishCertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authorizationInfo", Order=3)]
        public AuthorizationInfoType[] authorizationInfo
        {
            get
            {
                return this.authorizationInfoField;
            }
            set
            {
                this.authorizationInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public PollingPolicyType pollingPolicy
        {
            get
            {
                return this.pollingPolicyField;
            }
            set
            {
                this.pollingPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public enum PublishCert
    {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        clientProvided,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class ServiceEndpointType
    {
        
        private string typeField;
        
        private string endpointURIField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string endpointURI
        {
            get
            {
                return this.endpointURIField;
            }
            set
            {
                this.endpointURIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class PersonalInfoType
    {
        
        private string nameField;
        
        private string emailField;
        
        private string phoneField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class SystemInformation
    {
        
        private AttributeNameValuePairType[] searchCertificateDataField;
        
        private PublishCert cACertPublishField;
        
        private bool cACertPublishFieldSpecified;
        
        private CACertPublishNameValuePair cACertPublishNameValuePairField;
        
        private bool cACertPublishNameValuePairFieldSpecified;
        
        private DeliveryFormat certificateDeliveryFormatField;
        
        private PersonalInfoType adminInfoField;
        
        private ServiceEndpointType[] serviceEndpointListField;
        
        private string duplicateCertPolicyField;
        
        private string supersededPolicyOIDField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("searchAttributeNameValuePair", IsNullable=false)]
        public AttributeNameValuePairType[] searchCertificateData
        {
            get
            {
                return this.searchCertificateDataField;
            }
            set
            {
                this.searchCertificateDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PublishCert cACertPublish
        {
            get
            {
                return this.cACertPublishField;
            }
            set
            {
                this.cACertPublishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cACertPublishSpecified
        {
            get
            {
                return this.cACertPublishFieldSpecified;
            }
            set
            {
                this.cACertPublishFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CACertPublishNameValuePair cACertPublishNameValuePair
        {
            get
            {
                return this.cACertPublishNameValuePairField;
            }
            set
            {
                this.cACertPublishNameValuePairField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cACertPublishNameValuePairSpecified
        {
            get
            {
                return this.cACertPublishNameValuePairFieldSpecified;
            }
            set
            {
                this.cACertPublishNameValuePairFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DeliveryFormat certificateDeliveryFormat
        {
            get
            {
                return this.certificateDeliveryFormatField;
            }
            set
            {
                this.certificateDeliveryFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PersonalInfoType adminInfo
        {
            get
            {
                return this.adminInfoField;
            }
            set
            {
                this.adminInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceEndpoint", IsNullable=false)]
        public ServiceEndpointType[] serviceEndpointList
        {
            get
            {
                return this.serviceEndpointListField;
            }
            set
            {
                this.serviceEndpointListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string duplicateCertPolicy
        {
            get
            {
                return this.duplicateCertPolicyField;
            }
            set
            {
                this.duplicateCertPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string supersededPolicyOID
        {
            get
            {
                return this.supersededPolicyOIDField;
            }
            set
            {
                this.supersededPolicyOIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=8)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class AttributeNameValuePairType
    {
        
        private string attributeNameField;
        
        private AttributeValueType attributeNameValueField;
        
        private AttributeNameValuePropertyType attributeNameValuePropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string attributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public AttributeValueType attributeNameValue
        {
            get
            {
                return this.attributeNameValueField;
            }
            set
            {
                this.attributeNameValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AttributeNameValuePropertyType attributeNameValueProperty
        {
            get
            {
                return this.attributeNameValuePropertyField;
            }
            set
            {
                this.attributeNameValuePropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public enum CACertPublishNameValuePair
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("$publish_flag")]
        publish_flag,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public enum DeliveryFormat
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X5" +
            "09v3")]
        httpdocsoasisopenorgwss200401oasis200401wssx509tokenprofile10X509v3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#PK" +
            "CS7")]
        httpdocsoasisopenorgwss200401oasis200401wssx509tokenprofile10PKCS7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://schemas.verisign.com/pkiservices/2009/07/PKCS12")]
        httpschemasverisigncompkiservices200907PKCS12,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class ClientPolicy
    {
        
        private string clientNameField;
        
        private int maxPinLengthField;
        
        private bool maxPinLengthFieldSpecified;
        
        private int minPinLengthField;
        
        private bool minPinLengthFieldSpecified;
        
        private int noOfBadAttemptsField;
        
        private bool noOfBadAttemptsFieldSpecified;
        
        private int certRenewalOverlapField;
        
        private bool certRenewalOverlapFieldSpecified;
        
        private bool renewExpiredCertsField;
        
        private bool renewExpiredCertsFieldSpecified;
        
        private string certRenewalMsgField;
        
        private bool certCleanUpField;
        
        private bool certCleanUpFieldSpecified;
        
        private PublishCert certPublishField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int maxPinLength
        {
            get
            {
                return this.maxPinLengthField;
            }
            set
            {
                this.maxPinLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPinLengthSpecified
        {
            get
            {
                return this.maxPinLengthFieldSpecified;
            }
            set
            {
                this.maxPinLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int minPinLength
        {
            get
            {
                return this.minPinLengthField;
            }
            set
            {
                this.minPinLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minPinLengthSpecified
        {
            get
            {
                return this.minPinLengthFieldSpecified;
            }
            set
            {
                this.minPinLengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int noOfBadAttempts
        {
            get
            {
                return this.noOfBadAttemptsField;
            }
            set
            {
                this.noOfBadAttemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool noOfBadAttemptsSpecified
        {
            get
            {
                return this.noOfBadAttemptsFieldSpecified;
            }
            set
            {
                this.noOfBadAttemptsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int certRenewalOverlap
        {
            get
            {
                return this.certRenewalOverlapField;
            }
            set
            {
                this.certRenewalOverlapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certRenewalOverlapSpecified
        {
            get
            {
                return this.certRenewalOverlapFieldSpecified;
            }
            set
            {
                this.certRenewalOverlapFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool renewExpiredCerts
        {
            get
            {
                return this.renewExpiredCertsField;
            }
            set
            {
                this.renewExpiredCertsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool renewExpiredCertsSpecified
        {
            get
            {
                return this.renewExpiredCertsFieldSpecified;
            }
            set
            {
                this.renewExpiredCertsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string certRenewalMsg
        {
            get
            {
                return this.certRenewalMsgField;
            }
            set
            {
                this.certRenewalMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool certCleanUp
        {
            get
            {
                return this.certCleanUpField;
            }
            set
            {
                this.certCleanUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certCleanUpSpecified
        {
            get
            {
                return this.certCleanUpFieldSpecified;
            }
            set
            {
                this.certCleanUpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public PublishCert certPublish
        {
            get
            {
                return this.certPublishField;
            }
            set
            {
                this.certPublishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=9)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class KeyEscrowPolicyType
    {
        
        private bool keyEscrowEnabledField;
        
        private bool keyRecoveryDualAdminApprovalRequiredField;
        
        private bool keyRecoveryDualAdminApprovalRequiredFieldSpecified;
        
        private string keyEscrowDeploymentModeField;
        
        private System.Nullable<bool> doKeyRecoveryForAdditionalEnrollRequestField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool keyEscrowEnabled
        {
            get
            {
                return this.keyEscrowEnabledField;
            }
            set
            {
                this.keyEscrowEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool keyRecoveryDualAdminApprovalRequired
        {
            get
            {
                return this.keyRecoveryDualAdminApprovalRequiredField;
            }
            set
            {
                this.keyRecoveryDualAdminApprovalRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keyRecoveryDualAdminApprovalRequiredSpecified
        {
            get
            {
                return this.keyRecoveryDualAdminApprovalRequiredFieldSpecified;
            }
            set
            {
                this.keyRecoveryDualAdminApprovalRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string keyEscrowDeploymentMode
        {
            get
            {
                return this.keyEscrowDeploymentModeField;
            }
            set
            {
                this.keyEscrowDeploymentModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> doKeyRecoveryForAdditionalEnrollRequest
        {
            get
            {
                return this.doKeyRecoveryForAdditionalEnrollRequestField;
            }
            set
            {
                this.doKeyRecoveryForAdditionalEnrollRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class PrivateKeyInfo
    {
        
        private int keysizeField;
        
        private KeyEscrowPolicyType keyEscrowPolicyField;
        
        private bool keyexportableField;
        
        private bool keyprotectField;
        
        private bool keyprotectFieldSpecified;
        
        private System.Nullable<int> algorithmOIDReferenceField;
        
        private string[] cryptoProvidersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int keysize
        {
            get
            {
                return this.keysizeField;
            }
            set
            {
                this.keysizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public KeyEscrowPolicyType keyEscrowPolicy
        {
            get
            {
                return this.keyEscrowPolicyField;
            }
            set
            {
                this.keyEscrowPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool keyexportable
        {
            get
            {
                return this.keyexportableField;
            }
            set
            {
                this.keyexportableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool keyprotect
        {
            get
            {
                return this.keyprotectField;
            }
            set
            {
                this.keyprotectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keyprotectSpecified
        {
            get
            {
                return this.keyprotectFieldSpecified;
            }
            set
            {
                this.keyprotectFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> algorithmOIDReference
        {
            get
            {
                return this.algorithmOIDReferenceField;
            }
            set
            {
                this.algorithmOIDReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("provider", IsNullable=false)]
        public string[] cryptoProviders
        {
            get
            {
                return this.cryptoProvidersField;
            }
            set
            {
                this.cryptoProvidersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class extensionValueType
    {
        
        private bool mandatoryField;
        
        private bool mandatoryFieldSpecified;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool mandatory
        {
            get
            {
                return this.mandatoryField;
            }
            set
            {
                this.mandatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandatorySpecified
        {
            get
            {
                return this.mandatoryFieldSpecified;
            }
            set
            {
                this.mandatoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class extensionSyntax
    {
        
        private object[] itemsField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extensionAttributeNameValuePair", typeof(AttributeNameValuePairType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("extensionValue", typeof(extensionValueType), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class Extension
    {
        
        private int extensionOIDReferenceField;
        
        private bool extensionCriticalFlagField;
        
        private extensionSyntax extensionSyntaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int extensionOIDReference
        {
            get
            {
                return this.extensionOIDReferenceField;
            }
            set
            {
                this.extensionOIDReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool extensionCriticalFlag
        {
            get
            {
                return this.extensionCriticalFlagField;
            }
            set
            {
                this.extensionCriticalFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public extensionSyntax extensionSyntax
        {
            get
            {
                return this.extensionSyntaxField;
            }
            set
            {
                this.extensionSyntaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class subjectNameAttribute
    {
        
        private System.Nullable<int> subjectNameAttributecountField;
        
        private AttributeNameValuePairType[] subjectNameAttributeNameValuePairField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> subjectNameAttributecount
        {
            get
            {
                return this.subjectNameAttributecountField;
            }
            set
            {
                this.subjectNameAttributecountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subjectNameAttributeNameValuePair", Order=1)]
        public AttributeNameValuePairType[] subjectNameAttributeNameValuePair
        {
            get
            {
                return this.subjectNameAttributeNameValuePairField;
            }
            set
            {
                this.subjectNameAttributeNameValuePairField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class subjectName
    {
        
        private subjectNameAttribute[] subjectNameAttributeField;
        
        private bool overrideSubjectNameFormatField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subjectNameAttribute", Order=0)]
        public subjectNameAttribute[] subjectNameAttribute
        {
            get
            {
                return this.subjectNameAttributeField;
            }
            set
            {
                this.subjectNameAttributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool overrideSubjectNameFormat
        {
            get
            {
                return this.overrideSubjectNameFormatField;
            }
            set
            {
                this.overrideSubjectNameFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class OverrideValidity
    {
        
        private bool overrideFlagField;
        
        private bool overrideFlagFieldSpecified;
        
        private validityNameValuePairNames[] overrideNameValuePairField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool overrideFlag
        {
            get
            {
                return this.overrideFlagField;
            }
            set
            {
                this.overrideFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overrideFlagSpecified
        {
            get
            {
                return this.overrideFlagFieldSpecified;
            }
            set
            {
                this.overrideFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("overrideNameValuePair", Order=1)]
        public validityNameValuePairNames[] overrideNameValuePair
        {
            get
            {
                return this.overrideNameValuePairField;
            }
            set
            {
                this.overrideNameValuePairField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public enum validityNameValuePairNames
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("$overrideValidityDays")]
        overrideValidityDays,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("$overrideValidityStartDate")]
        overrideValidityStartDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("$overrideValidityEndDate")]
        overrideValidityEndDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class CertificateValidity
    {
        
        private ulong validityPeriodDaysField;
        
        private ulong renewalPeriodDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong validityPeriodDays
        {
            get
            {
                return this.validityPeriodDaysField;
            }
            set
            {
                this.validityPeriodDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ulong renewalPeriodDays
        {
            get
            {
                return this.renewalPeriodDaysField;
            }
            set
            {
                this.renewalPeriodDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class Attributes
    {
        
        private int policySchemaField;
        
        private CertificateValidity certificateValidityField;
        
        private OverrideValidity certificateOverrideValidityField;
        
        private subjectName subjectNameInfoField;
        
        private Extension[] extensionsField;
        
        private PrivateKeyInfo privateKeyAttributesField;
        
        private ClientPolicy clientPolicyField;
        
        private SystemInformation systemInfoField;
        
        private RAPolicy rAPolicyField;
        
        private SeatInfoType seatIdInfoField;
        
        private ApplicationInstructionsType applicationInstructionsField;
        
        private string deploymentModeField;
        
        private string statusField;
        
        private MigrationOIDCollection migrationOIDsField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int policySchema
        {
            get
            {
                return this.policySchemaField;
            }
            set
            {
                this.policySchemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CertificateValidity certificateValidity
        {
            get
            {
                return this.certificateValidityField;
            }
            set
            {
                this.certificateValidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OverrideValidity certificateOverrideValidity
        {
            get
            {
                return this.certificateOverrideValidityField;
            }
            set
            {
                this.certificateOverrideValidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public subjectName subjectNameInfo
        {
            get
            {
                return this.subjectNameInfoField;
            }
            set
            {
                this.subjectNameInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Extension[] extensions
        {
            get
            {
                return this.extensionsField;
            }
            set
            {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public PrivateKeyInfo privateKeyAttributes
        {
            get
            {
                return this.privateKeyAttributesField;
            }
            set
            {
                this.privateKeyAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public ClientPolicy clientPolicy
        {
            get
            {
                return this.clientPolicyField;
            }
            set
            {
                this.clientPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public SystemInformation systemInfo
        {
            get
            {
                return this.systemInfoField;
            }
            set
            {
                this.systemInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public RAPolicy rAPolicy
        {
            get
            {
                return this.rAPolicyField;
            }
            set
            {
                this.rAPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public SeatInfoType seatIdInfo
        {
            get
            {
                return this.seatIdInfoField;
            }
            set
            {
                this.seatIdInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public ApplicationInstructionsType applicationInstructions
        {
            get
            {
                return this.applicationInstructionsField;
            }
            set
            {
                this.applicationInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string deploymentMode
        {
            get
            {
                return this.deploymentModeField;
            }
            set
            {
                this.deploymentModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public MigrationOIDCollection migrationOIDs
        {
            get
            {
                return this.migrationOIDsField;
            }
            set
            {
                this.migrationOIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=14)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class CertificateEnrollmentPolicy
    {
        
        private int policyOIDReferenceField;
        
        private int[] cAsField;
        
        private Attributes attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int policyOIDReference
        {
            get
            {
                return this.policyOIDReferenceField;
            }
            set
            {
                this.policyOIDReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("cAReference", IsNullable=false)]
        public int[] cAs
        {
            get
            {
                return this.cAsField;
            }
            set
            {
                this.cAsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Attributes attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class Response
    {
        
        private string policyIDField;
        
        private string policyFriendlyNameField;
        
        private System.Nullable<uint> nextUpdateHoursField;
        
        private bool policiesNotChangedField;
        
        private CertificateEnrollmentPolicy[] policiesField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string policyID
        {
            get
            {
                return this.policyIDField;
            }
            set
            {
                this.policyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string policyFriendlyName
        {
            get
            {
                return this.policyFriendlyNameField;
            }
            set
            {
                this.policyFriendlyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<uint> nextUpdateHours
        {
            get
            {
                return this.nextUpdateHoursField;
            }
            set
            {
                this.nextUpdateHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool policiesNotChanged
        {
            get
            {
                return this.policiesNotChangedField;
            }
            set
            {
                this.policiesNotChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("policy", IsNullable=false)]
        public CertificateEnrollmentPolicy[] policies
        {
            get
            {
                return this.policiesField;
            }
            set
            {
                this.policiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class RequestFilter
    {
        
        private string[] policyIDsField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("oid", IsNullable=false)]
        public string[] policyIDs
        {
            get
            {
                return this.policyIDsField;
            }
            set
            {
                this.policyIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy")]
    public partial class getPoliciesResponse
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private Response responseField;
        
        private CA[] cAsField;
        
        private OID[] oIDsField;
        
        private byte[] signedEnrollmentPolicyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Response response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("cA", IsNullable=false)]
        public CA[] cAs
        {
            get
            {
                return this.cAsField;
            }
            set
            {
                this.cAsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("oID", IsNullable=false)]
        public OID[] oIDs
        {
            get
            {
                return this.oIDsField;
            }
            set
            {
                this.oIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] signedEnrollmentPolicy
        {
            get
            {
                return this.signedEnrollmentPolicyField;
            }
            set
            {
                this.signedEnrollmentPolicyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestPoliciesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy", Order=0)]
        public DigiCert.Demo.Policy.getPolicies getPolicies;
        
        public requestPoliciesRequest()
        {
        }
        
        public requestPoliciesRequest(DigiCert.Demo.Policy.getPolicies getPolicies)
        {
            this.getPolicies = getPolicies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestPoliciesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.verisign.com/pkiservices/2009/07/policy", Order=0)]
        public DigiCert.Demo.Policy.getPoliciesResponse getPoliciesResponse;
        
        public requestPoliciesResponse()
        {
        }
        
        public requestPoliciesResponse(DigiCert.Demo.Policy.getPoliciesResponse getPoliciesResponse)
        {
            this.getPoliciesResponse = getPoliciesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface policyChannel : DigiCert.Demo.Policy.policy, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class policyClient : System.ServiceModel.ClientBase<DigiCert.Demo.Policy.policy>, DigiCert.Demo.Policy.policy
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public policyClient() : 
                base(policyClient.GetDefaultBinding(), policyClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.requestPoliciesServiceSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public policyClient(EndpointConfiguration endpointConfiguration) : 
                base(policyClient.GetBindingForEndpoint(endpointConfiguration), policyClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public policyClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(policyClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public policyClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(policyClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public policyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.Policy.requestPoliciesResponse> DigiCert.Demo.Policy.policy.requestPoliciesAsync(DigiCert.Demo.Policy.requestPoliciesRequest request)
        {
            return base.Channel.requestPoliciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.Policy.requestPoliciesResponse> requestPoliciesAsync(DigiCert.Demo.Policy.getPolicies getPolicies)
        {
            DigiCert.Demo.Policy.requestPoliciesRequest inValue = new DigiCert.Demo.Policy.requestPoliciesRequest();
            inValue.getPolicies = getPolicies;
            return ((DigiCert.Demo.Policy.policy)(this)).requestPoliciesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.requestPoliciesServiceSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.requestPoliciesServiceSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://pki-ws.symauth.com/pki-ws/policyService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return policyClient.GetBindingForEndpoint(EndpointConfiguration.requestPoliciesServiceSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return policyClient.GetEndpointAddress(EndpointConfiguration.requestPoliciesServiceSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            requestPoliciesServiceSOAP,
        }
    }
}
