//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiCert.Demo.UserManagement
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", ConfigurationName="DigiCert.Demo.UserManagement.userManagementOperations")]
    public interface userManagementOperations
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/createOrUpdateUserRequest", ReplyAction="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/createOrUpdateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.createOrUpdateUserResponse> createOrUpdateUserAsync(DigiCert.Demo.UserManagement.createOrUpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/createOrUpdatePasscodeRequest", ReplyAction="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/createOrUpdatePasscodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.createOrUpdatePasscodeResponse> createOrUpdatePasscodeAsync(DigiCert.Demo.UserManagement.createOrUpdatePasscodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/deleteUserRequest", ReplyAction="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/deleteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.deleteUserResponse> deleteUserAsync(DigiCert.Demo.UserManagement.deleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/bulkDeleteUserRequest", ReplyAction="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/bulkDeleteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.bulkDeleteUserResponse> bulkDeleteUserAsync(DigiCert.Demo.UserManagement.bulkDeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/getPasscodeInformationRequest", ReplyAction="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/getPasscodeInformationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.getPasscodeInformationResponse> getPasscodeInformationAsync(DigiCert.Demo.UserManagement.getPasscodeInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/getUserInformationRequest", ReplyAction="http://schemas.verisign.com/pkiservices/2011/08/usermanagement/userManagementOper" +
            "ations/getUserInformationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.getUserInformationResponse> getUserInformationAsync(DigiCert.Demo.UserManagement.getUserInformationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class CreateOrUpdateUserRequestMessageType
    {
        
        private string clientTransactionIDField;
        
        private UserInformationType[] userInformationField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userInformation", Order=1)]
        public UserInformationType[] userInformation
        {
            get
            {
                return this.userInformationField;
            }
            set
            {
                this.userInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class UserInformationType
    {
        
        private string seatIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailAddressField;
        
        private string deskPhoneNumberField;
        
        private string mobilePhoneNumberField;
        
        private NameValueType[] userAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string emailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string deskPhoneNumber
        {
            get
            {
                return this.deskPhoneNumberField;
            }
            set
            {
                this.deskPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string mobilePhoneNumber
        {
            get
            {
                return this.mobilePhoneNumberField;
            }
            set
            {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userAttribute", Order=6)]
        public NameValueType[] userAttribute
        {
            get
            {
                return this.userAttributeField;
            }
            set
            {
                this.userAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class NameValueType
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class GetUserInformationResponseMessageType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private UserInformationType userInformationField;
        
        private string[] userValidCertificatesField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UserInformationType userInformation
        {
            get
            {
                return this.userInformationField;
            }
            set
            {
                this.userInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("userCertificate", IsNullable=false)]
        public string[] userValidCertificates
        {
            get
            {
                return this.userValidCertificatesField;
            }
            set
            {
                this.userValidCertificatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class GetUserInformationRequestMessageType
    {
        
        private string clientTransactionIDField;
        
        private string seatIdField;
        
        private bool getUserCertificateField;
        
        private bool getUserCertificateFieldSpecified;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool getUserCertificate
        {
            get
            {
                return this.getUserCertificateField;
            }
            set
            {
                this.getUserCertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool getUserCertificateSpecified
        {
            get
            {
                return this.getUserCertificateFieldSpecified;
            }
            set
            {
                this.getUserCertificateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class GetPasscodeInformationResponseMessageType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private PasscodeInformationType passcodeInformationField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PasscodeInformationType passcodeInformation
        {
            get
            {
                return this.passcodeInformationField;
            }
            set
            {
                this.passcodeInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class PasscodeInformationType
    {
        
        private string passcodeField;
        
        private int numberOfBadAttemptsField;
        
        private bool numberOfBadAttemptsFieldSpecified;
        
        private string passcodeStatusField;
        
        private System.DateTime expiryDateTimeField;
        
        private bool expiryDateTimeFieldSpecified;
        
        private System.DateTime creationDateTimeField;
        
        private bool creationDateTimeFieldSpecified;
        
        private string seatIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string certificateProfileOidField;
        
        private string enrollmentURLField;
        
        private NameValueType[] userAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string passcode
        {
            get
            {
                return this.passcodeField;
            }
            set
            {
                this.passcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int numberOfBadAttempts
        {
            get
            {
                return this.numberOfBadAttemptsField;
            }
            set
            {
                this.numberOfBadAttemptsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberOfBadAttemptsSpecified
        {
            get
            {
                return this.numberOfBadAttemptsFieldSpecified;
            }
            set
            {
                this.numberOfBadAttemptsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string passcodeStatus
        {
            get
            {
                return this.passcodeStatusField;
            }
            set
            {
                this.passcodeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime expiryDateTime
        {
            get
            {
                return this.expiryDateTimeField;
            }
            set
            {
                this.expiryDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateTimeSpecified
        {
            get
            {
                return this.expiryDateTimeFieldSpecified;
            }
            set
            {
                this.expiryDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime creationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationDateTimeSpecified
        {
            get
            {
                return this.creationDateTimeFieldSpecified;
            }
            set
            {
                this.creationDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string certificateProfileOid
        {
            get
            {
                return this.certificateProfileOidField;
            }
            set
            {
                this.certificateProfileOidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string enrollmentURL
        {
            get
            {
                return this.enrollmentURLField;
            }
            set
            {
                this.enrollmentURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userAttribute", Order=11)]
        public NameValueType[] userAttribute
        {
            get
            {
                return this.userAttributeField;
            }
            set
            {
                this.userAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class GetPasscodeInformationRequestMessageType
    {
        
        private string clientTransactionIDField;
        
        private string seatIdField;
        
        private string certificateProfileOidField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string certificateProfileOid
        {
            get
            {
                return this.certificateProfileOidField;
            }
            set
            {
                this.certificateProfileOidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class BulkDeleteUserResponseMessageType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private DeleteUserStatusType[] deleteUserStatusField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deleteUserStatus", Order=2)]
        public DeleteUserStatusType[] deleteUserStatus
        {
            get
            {
                return this.deleteUserStatusField;
            }
            set
            {
                this.deleteUserStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class DeleteUserStatusType
    {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string seatIdField;
        
        private int revocationCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int revocationCount
        {
            get
            {
                return this.revocationCountField;
            }
            set
            {
                this.revocationCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class BulkDeleteUserRequestMessageType
    {
        
        private string clientTransactionIDField;
        
        private string[] seatIdField;
        
        private RevokeReasonCodeEnum revocationReasonField;
        
        private bool revocationReasonFieldSpecified;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seatId", Order=1)]
        public string[] seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RevokeReasonCodeEnum revocationReason
        {
            get
            {
                return this.revocationReasonField;
            }
            set
            {
                this.revocationReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revocationReasonSpecified
        {
            get
            {
                return this.revocationReasonFieldSpecified;
            }
            set
            {
                this.revocationReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public enum RevokeReasonCodeEnum
    {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        KeyCompromise,
        
        /// <remarks/>
        CACompromise,
        
        /// <remarks/>
        AffiliationChanged,
        
        /// <remarks/>
        CessationOfOperation,
        
        /// <remarks/>
        PrivilegeWithdrawn,
        
        /// <remarks/>
        AACompromise,
        
        /// <remarks/>
        Superseded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class DeleteUserResponseMessageType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private DeleteUserStatusType deleteUserStatusField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DeleteUserStatusType deleteUserStatus
        {
            get
            {
                return this.deleteUserStatusField;
            }
            set
            {
                this.deleteUserStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class DeleteUserRequestMessageType
    {
        
        private string clientTransactionIDField;
        
        private string seatIdField;
        
        private RevokeReasonCodeEnum revocationReasonField;
        
        private bool revocationReasonFieldSpecified;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RevokeReasonCodeEnum revocationReason
        {
            get
            {
                return this.revocationReasonField;
            }
            set
            {
                this.revocationReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revocationReasonSpecified
        {
            get
            {
                return this.revocationReasonFieldSpecified;
            }
            set
            {
                this.revocationReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class PasscodeCreationStatusType
    {
        
        private PasscodeInformationType passcodeInformationField;
        
        private string statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PasscodeInformationType passcodeInformation
        {
            get
            {
                return this.passcodeInformationField;
            }
            set
            {
                this.passcodeInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class CreateOrUpdatePasscodeResponseMessageType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private PasscodeCreationStatusType[] passcodeCreationStatusField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("passcodeCreationStatus", Order=2)]
        public PasscodeCreationStatusType[] passcodeCreationStatus
        {
            get
            {
                return this.passcodeCreationStatusField;
            }
            set
            {
                this.passcodeCreationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class CreateOrUpdatePasscodeRequestMessageType
    {
        
        private string clientTransactionIDField;
        
        private PasscodeInformationType[] passcodeInformationField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("passcodeInformation", Order=1)]
        public PasscodeInformationType[] passcodeInformation
        {
            get
            {
                return this.passcodeInformationField;
            }
            set
            {
                this.passcodeInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class UserCreationStatusType
    {
        
        private string seatIdField;
        
        private string statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string seatId
        {
            get
            {
                return this.seatIdField;
            }
            set
            {
                this.seatIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement")]
    public partial class CreateOrUpdateUserResponseMessageType
    {
        
        private string clientTransactionIDField;
        
        private string serverTransactionIDField;
        
        private UserCreationStatusType[] userCreationStatusField;
        
        private string versionField;
        
        private System.Xml.Linq.XElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientTransactionID
        {
            get
            {
                return this.clientTransactionIDField;
            }
            set
            {
                this.clientTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverTransactionID
        {
            get
            {
                return this.serverTransactionIDField;
            }
            set
            {
                this.serverTransactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userCreationStatus", Order=2)]
        public UserCreationStatusType[] userCreationStatus
        {
            get
            {
                return this.userCreationStatusField;
            }
            set
            {
                this.userCreationStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createOrUpdateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createOrUpdateUserRequest", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.CreateOrUpdateUserRequestMessageType createOrUpdateUserRequest1;
        
        public createOrUpdateUserRequest()
        {
        }
        
        public createOrUpdateUserRequest(DigiCert.Demo.UserManagement.CreateOrUpdateUserRequestMessageType createOrUpdateUserRequest1)
        {
            this.createOrUpdateUserRequest1 = createOrUpdateUserRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createOrUpdateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createOrUpdateUserResponse", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.CreateOrUpdateUserResponseMessageType createOrUpdateUserResponse1;
        
        public createOrUpdateUserResponse()
        {
        }
        
        public createOrUpdateUserResponse(DigiCert.Demo.UserManagement.CreateOrUpdateUserResponseMessageType createOrUpdateUserResponse1)
        {
            this.createOrUpdateUserResponse1 = createOrUpdateUserResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createOrUpdatePasscodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createOrUpdatePasscodeRequest", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.CreateOrUpdatePasscodeRequestMessageType createOrUpdatePasscodeRequest1;
        
        public createOrUpdatePasscodeRequest()
        {
        }
        
        public createOrUpdatePasscodeRequest(DigiCert.Demo.UserManagement.CreateOrUpdatePasscodeRequestMessageType createOrUpdatePasscodeRequest1)
        {
            this.createOrUpdatePasscodeRequest1 = createOrUpdatePasscodeRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createOrUpdatePasscodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createOrUpdatePasscodeResponse", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.CreateOrUpdatePasscodeResponseMessageType createOrUpdatePasscodeResponse1;
        
        public createOrUpdatePasscodeResponse()
        {
        }
        
        public createOrUpdatePasscodeResponse(DigiCert.Demo.UserManagement.CreateOrUpdatePasscodeResponseMessageType createOrUpdatePasscodeResponse1)
        {
            this.createOrUpdatePasscodeResponse1 = createOrUpdatePasscodeResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteUserRequest", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.DeleteUserRequestMessageType deleteUserRequest1;
        
        public deleteUserRequest()
        {
        }
        
        public deleteUserRequest(DigiCert.Demo.UserManagement.DeleteUserRequestMessageType deleteUserRequest1)
        {
            this.deleteUserRequest1 = deleteUserRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteUserResponse", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.DeleteUserResponseMessageType deleteUserResponse1;
        
        public deleteUserResponse()
        {
        }
        
        public deleteUserResponse(DigiCert.Demo.UserManagement.DeleteUserResponseMessageType deleteUserResponse1)
        {
            this.deleteUserResponse1 = deleteUserResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bulkDeleteUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bulkDeleteUserRequest", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.BulkDeleteUserRequestMessageType bulkDeleteUserRequest1;
        
        public bulkDeleteUserRequest()
        {
        }
        
        public bulkDeleteUserRequest(DigiCert.Demo.UserManagement.BulkDeleteUserRequestMessageType bulkDeleteUserRequest1)
        {
            this.bulkDeleteUserRequest1 = bulkDeleteUserRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bulkDeleteUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bulkDeleteUserResponse", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.BulkDeleteUserResponseMessageType bulkDeleteUserResponse1;
        
        public bulkDeleteUserResponse()
        {
        }
        
        public bulkDeleteUserResponse(DigiCert.Demo.UserManagement.BulkDeleteUserResponseMessageType bulkDeleteUserResponse1)
        {
            this.bulkDeleteUserResponse1 = bulkDeleteUserResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPasscodeInformationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPasscodeInformationRequest", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.GetPasscodeInformationRequestMessageType getPasscodeInformationRequest1;
        
        public getPasscodeInformationRequest()
        {
        }
        
        public getPasscodeInformationRequest(DigiCert.Demo.UserManagement.GetPasscodeInformationRequestMessageType getPasscodeInformationRequest1)
        {
            this.getPasscodeInformationRequest1 = getPasscodeInformationRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPasscodeInformationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPasscodeInformationResponse", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.GetPasscodeInformationResponseMessageType getPasscodeInformationResponse1;
        
        public getPasscodeInformationResponse()
        {
        }
        
        public getPasscodeInformationResponse(DigiCert.Demo.UserManagement.GetPasscodeInformationResponseMessageType getPasscodeInformationResponse1)
        {
            this.getPasscodeInformationResponse1 = getPasscodeInformationResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInformationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInformationRequest", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.GetUserInformationRequestMessageType getUserInformationRequest1;
        
        public getUserInformationRequest()
        {
        }
        
        public getUserInformationRequest(DigiCert.Demo.UserManagement.GetUserInformationRequestMessageType getUserInformationRequest1)
        {
            this.getUserInformationRequest1 = getUserInformationRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInformationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInformationResponse", Namespace="http://schemas.verisign.com/pkiservices/2011/08/usermanagement", Order=0)]
        public DigiCert.Demo.UserManagement.GetUserInformationResponseMessageType getUserInformationResponse1;
        
        public getUserInformationResponse()
        {
        }
        
        public getUserInformationResponse(DigiCert.Demo.UserManagement.GetUserInformationResponseMessageType getUserInformationResponse1)
        {
            this.getUserInformationResponse1 = getUserInformationResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface userManagementOperationsChannel : DigiCert.Demo.UserManagement.userManagementOperations, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class userManagementOperationsClient : System.ServiceModel.ClientBase<DigiCert.Demo.UserManagement.userManagementOperations>, DigiCert.Demo.UserManagement.userManagementOperations
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public userManagementOperationsClient() : 
                base(userManagementOperationsClient.GetDefaultBinding(), userManagementOperationsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.userManagementServiceSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public userManagementOperationsClient(EndpointConfiguration endpointConfiguration) : 
                base(userManagementOperationsClient.GetBindingForEndpoint(endpointConfiguration), userManagementOperationsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public userManagementOperationsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(userManagementOperationsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public userManagementOperationsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(userManagementOperationsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public userManagementOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.createOrUpdateUserResponse> DigiCert.Demo.UserManagement.userManagementOperations.createOrUpdateUserAsync(DigiCert.Demo.UserManagement.createOrUpdateUserRequest request)
        {
            return base.Channel.createOrUpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.createOrUpdateUserResponse> createOrUpdateUserAsync(DigiCert.Demo.UserManagement.CreateOrUpdateUserRequestMessageType createOrUpdateUserRequest1)
        {
            DigiCert.Demo.UserManagement.createOrUpdateUserRequest inValue = new DigiCert.Demo.UserManagement.createOrUpdateUserRequest();
            inValue.createOrUpdateUserRequest1 = createOrUpdateUserRequest1;
            return ((DigiCert.Demo.UserManagement.userManagementOperations)(this)).createOrUpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.createOrUpdatePasscodeResponse> DigiCert.Demo.UserManagement.userManagementOperations.createOrUpdatePasscodeAsync(DigiCert.Demo.UserManagement.createOrUpdatePasscodeRequest request)
        {
            return base.Channel.createOrUpdatePasscodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.createOrUpdatePasscodeResponse> createOrUpdatePasscodeAsync(DigiCert.Demo.UserManagement.CreateOrUpdatePasscodeRequestMessageType createOrUpdatePasscodeRequest1)
        {
            DigiCert.Demo.UserManagement.createOrUpdatePasscodeRequest inValue = new DigiCert.Demo.UserManagement.createOrUpdatePasscodeRequest();
            inValue.createOrUpdatePasscodeRequest1 = createOrUpdatePasscodeRequest1;
            return ((DigiCert.Demo.UserManagement.userManagementOperations)(this)).createOrUpdatePasscodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.deleteUserResponse> DigiCert.Demo.UserManagement.userManagementOperations.deleteUserAsync(DigiCert.Demo.UserManagement.deleteUserRequest request)
        {
            return base.Channel.deleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.deleteUserResponse> deleteUserAsync(DigiCert.Demo.UserManagement.DeleteUserRequestMessageType deleteUserRequest1)
        {
            DigiCert.Demo.UserManagement.deleteUserRequest inValue = new DigiCert.Demo.UserManagement.deleteUserRequest();
            inValue.deleteUserRequest1 = deleteUserRequest1;
            return ((DigiCert.Demo.UserManagement.userManagementOperations)(this)).deleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.bulkDeleteUserResponse> DigiCert.Demo.UserManagement.userManagementOperations.bulkDeleteUserAsync(DigiCert.Demo.UserManagement.bulkDeleteUserRequest request)
        {
            return base.Channel.bulkDeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.bulkDeleteUserResponse> bulkDeleteUserAsync(DigiCert.Demo.UserManagement.BulkDeleteUserRequestMessageType bulkDeleteUserRequest1)
        {
            DigiCert.Demo.UserManagement.bulkDeleteUserRequest inValue = new DigiCert.Demo.UserManagement.bulkDeleteUserRequest();
            inValue.bulkDeleteUserRequest1 = bulkDeleteUserRequest1;
            return ((DigiCert.Demo.UserManagement.userManagementOperations)(this)).bulkDeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.getPasscodeInformationResponse> DigiCert.Demo.UserManagement.userManagementOperations.getPasscodeInformationAsync(DigiCert.Demo.UserManagement.getPasscodeInformationRequest request)
        {
            return base.Channel.getPasscodeInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.getPasscodeInformationResponse> getPasscodeInformationAsync(DigiCert.Demo.UserManagement.GetPasscodeInformationRequestMessageType getPasscodeInformationRequest1)
        {
            DigiCert.Demo.UserManagement.getPasscodeInformationRequest inValue = new DigiCert.Demo.UserManagement.getPasscodeInformationRequest();
            inValue.getPasscodeInformationRequest1 = getPasscodeInformationRequest1;
            return ((DigiCert.Demo.UserManagement.userManagementOperations)(this)).getPasscodeInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.getUserInformationResponse> DigiCert.Demo.UserManagement.userManagementOperations.getUserInformationAsync(DigiCert.Demo.UserManagement.getUserInformationRequest request)
        {
            return base.Channel.getUserInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DigiCert.Demo.UserManagement.getUserInformationResponse> getUserInformationAsync(DigiCert.Demo.UserManagement.GetUserInformationRequestMessageType getUserInformationRequest1)
        {
            DigiCert.Demo.UserManagement.getUserInformationRequest inValue = new DigiCert.Demo.UserManagement.getUserInformationRequest();
            inValue.getUserInformationRequest1 = getUserInformationRequest1;
            return ((DigiCert.Demo.UserManagement.userManagementOperations)(this)).getUserInformationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.userManagementServiceSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.userManagementServiceSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://pki-ws.symauth.com/pki-ws/userManagementService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return userManagementOperationsClient.GetBindingForEndpoint(EndpointConfiguration.userManagementServiceSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return userManagementOperationsClient.GetEndpointAddress(EndpointConfiguration.userManagementServiceSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            userManagementServiceSOAP,
        }
    }
}
